PROJECT_NAME="testing"
PROJECT_VERSION="1.0.0"
RELEASE="enabled"
RETENTION_DAYS="1"
TESTING="disabled"
SONAR="disabled"
DOCKER_TAG="latest"
DOCKER_REPOSITORY="alvarogarciapiz"
PYTHON_VERSION="3.10"
PYTHON_DIST_DIR="./"
